name: Lint Commits

on: [push, pull_request]

jobs:
  commit-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v5
        with:
          config: "@commitlint/config-conventional"
