name: Notify PR Activity

on:
  pull_request:
    branches:
      - master  
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification on PR activity
        uses: slackapi/slack-github-action@v1
        with:
          payload: '{"text": "PR #${{ github.event.pull_request.number }} was ${{ github.event.action }} by @${{ github.actor }}."}'
        env:
          fix(SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}