name: Notify PR Activity

on:
  pull_request:
    branches:
      - master  
workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification on PR activity
        uses: peter-evans/slack-send@v1
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          text: "PR #${{ github.event.pull_request.number }} was ${{ github.event.action }} by @${{ github.actor }}."
