name: Release Automation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master  
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Determine release type from commits
        id: determine_release_type
        run: |
          RELEASE_TYPE="patch"

          # Iterar sobre todos los commits y buscar los tipos
          while IFS= read -r COMMIT_MESSAGE; do
            if echo "$COMMIT_MESSAGE" | grep -qE '^feat\('; then
              RELEASE_TYPE="major"
            elif echo "$COMMIT_MESSAGE" | grep -qE '^fix\('; then
              # Si hay un fix pero no hay "minor", se mantiene como patch
              [ "$RELEASE_TYPE" != "major" ] && RELEASE_TYPE="minor"
            elif echo "$COMMIT_MESSAGE" | grep -qE '^refactor\('; then
              [ "$RELEASE_TYPE" != "minor" ] && [ "$RELEASE_TYPE" != "major" ] && RELEASE_TYPE="patch"
            elif echo "$COMMIT_MESSAGE" | grep -qE '^test\('; then
              [ "$RELEASE_TYPE" != "minor" ] && [ "$RELEASE_TYPE" != "major" ] && RELEASE_TYPE="patch"
            fi
          done < <(git log origin/main..HEAD --pretty=format:"%s")

          echo "RELEASE_TYPE=${RELEASE_TYPE}" >> $GITHUB_ENV
          echo "Release type: $RELEASE_TYPE"

      - name: Determine new version
        id: determine_version
        run: |
          MAJOR=0
          MINOR=0
          PATCH=0

          # Obtener la última versión
          if git describe --tags --abbrev=0; then
            LAST_VERSION=$(git describe --tags --abbrev=0)
            MAJOR=$(echo $LAST_VERSION | cut -d. -f1 | cut -dv -f2)
            MINOR=$(echo $LAST_VERSION | cut -d. -f2)
            PATCH=$(echo $LAST_VERSION | cut -d. -f3)
          fi

          case $RELEASE_TYPE in
            major)
              MAJOR=$((MAJOR + 1))
              MINOR=0
              PATCH=0
              ;;
            minor)
              MINOR=$((MINOR + 1))
              PATCH=0
              ;;
            patch)
              PATCH=$((PATCH + 1))
              ;;
          esac

          NEW_VERSION="v${MAJOR}.${MINOR}.${PATCH}"
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
          echo "Nueva versión: $NEW_VERSION"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NEW_VERSION }}
          release_name: "Release ${{ env.NEW_VERSION }}"
          body: "Automated release based on commit messages."
          draft: false
          prerelease: false
