name: Release Automation

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract commit message
        id: extract_commit
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "COMMIT_MESSAGE=${COMMIT_MESSAGE}" >> $GITHUB_ENV
          
          if echo "${COMMIT_MESSAGE}" | grep -q 'fix('; then
            echo "RELEASE_TYPE=patch" >> $GITHUB_ENV
          elif echo "${COMMIT_MESSAGE}" | grep -q 'feat('; then
            echo "RELEASE_TYPE=minor" >> $GITHUB_ENV
          elif echo "${COMMIT_MESSAGE}" | grep -q 'refactor('; then
            echo "RELEASE_TYPE=patch" >> $GITHUB_ENV
          elif echo "${COMMIT_MESSAGE}" | grep -q 'test('; then
            echo "RELEASE_TYPE=patch" >> $GITHUB_ENV
          fi

      - name: Print release type
        run: echo "The release type is ${{ env.RELEASE_TYPE }}"
        