name: Release Automation

on:
  push:
    tags:
      - 'v*' 

jobs:
  release:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract tag information
        id: extract_tag
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
          
          if echo "${TAG_NAME}" | grep -q 'fix'; then
            echo "RELEASE_TYPE=minor" >> $GITHUB_ENV
          elif echo "${TAG_NAME}" | grep -q 'feat'; then
            echo "RELEASE_TYPE=major" >> $GITHUB_ENV
          elif echo "${TAG_NAME}" | grep -q 'refactor'; then
            echo "RELEASE_TYPE=patch" >> $GITHUB_ENV
          elif echo "${TAG_NAME}" | grep -q 'tests'; then
            echo "RELEASE_TYPE=patch" >> $GITHUB_ENV
          else
            echo "RELEASE_TYPE=unknown" >> $GITHUB_ENV
          fi